var good_perks = {
    groundpound: { id: "groundpound", type: 0, name: "Ground Pound", cost: 3, description: "Does a ground pound!" },
    dash: { id: "dash", type: 0, name: "Dash", cost: 3, description: "Does a dash!" },
    levitate: { id: "levitate", type: 0, name: "Levitation", cost: 1, description: "While held, levitate!" },
    resurface: { id: "resurface", type: 0, name: "Resurface", cost: 1, description: "Expell all your air for a quick boost upward while in water" },
    what_doesnt_kill_you: { id: "what_doesnt_kill_you", type: 1, name: "What Doesn't Kill You...", cost: 4, description: "Your damage is increased the lower your health is." },
    water_warrior: { id: "water_warrior", type: 0, name: "Summon Water Warior", cost: 6, description: "Form a warrior made of water. Sends enemies flying back, but can't survive much damage." },
    perfect_aim: { id: "perfect_aim", type: 0, name: "Perfect Aim", cost: 12, description: "Carry your arrow with water, guiding it exactly where your crosshair sits." },
    blood_cost: { id: "blood_cost", type: 1, name: "Blood Cost", cost: 0, description: "When out of hydration, supplement your own blood to use perks. You take damage equivalent to the cost." },
    animal_lover: { id: "animal_lover", type: 0, name: "Animal Lover", cost: 6, description: "Secrete phermones that make wild animals trust you. It's duration is affected by your §cCharm" },
    jelly_bubble: { id: "jelly_bubble", type: 1, name: "Jelly Bubble", cost: 6, description: "Coat the tip of your arrow with a massive glob of water. When the arrow lands, it creates a surface on the ground, taking on the aspects of any jellies applied to the bow" },
    hurricane: { id: "hurricane", type: 0, name: "Hurricane", cost: 10, description: "Create a small hurricane, that sucks in enemies nearby" },
    wave_slice: { id: "wave_slice", type: 0, name: "Wave", cost: 6, description: "When you swing your weapon, you also send out a thin wave of water, damaging and knocking back enemies." },
    arrow_recovery: { id: "arrow_recovery", type: 0, name: "Arrow Recovery", cost: 6, description: "Attach a string of mucus to arrows, allowing you to retrieve them automatically" },
    revenge_attack: { id: "revenge_attack", type: 0, name: "Backsplash", cost: 0, description: "When active, you have a chance to react to damage and shoot out water to block the attack. Chances increase with Mind Attribute Total" },
    lifesteal: { id: "lifesteal", type: 0, name: "Blood Siphon", cost: 2, description: "While active, your attack damage is halved. You restore the other half amount as health, and use up hydration at the same rate." },
    invisibility: { id: "refraction", type: 0, name: "Refraction", cost: 2, description: "While active, you use water to refract light around you, rendering you invisible" },
    conservationist: { id: "conservationist", type: 1, name: "Conservationist", cost: 6, description: "At the cost of 6 hydration, you continually replenish hydration." },
    ripple: { id: "ripple", type: 0, name: "Ripple Effect", cost: 4, description: "When in water, send out a large ripple, pushing enemies back and slightly damaging them" },
    birthday_armor: { id: "birthday_armor", type: 1, name: "Birthday Armor", cost: 8, description: "You do +2 damage for each empty slot of armor" },
    icicle: { id: "icicle", type: 0, name: "Icicile", cost: 6, description: "If a suitable ceiling is above you by (Deftness*4) blocks or less, form an icicle that you latch on to." }
}

var dampening_perks = {
    fragile_feet: { id: "fragile_feet", cost: 2, name: "Fragile Feet", description: "The threshold for fall damage is smaller, and it deals more damage" },
    frail_fingers: { id: "frail_fingers", cost: 2, name: "Frail Fingers", description: "Your grip on the bow string is unreliable." },
    social_anxiety: { id: "social_anxiety", cost: 4, name: "Social Anxiety", description: "You take damage upon failing an attribute roll." },
    winded: { id: "winded", name: "Winded", cost: 4, description: "Your sprint is slower" },
    pescetarian: { id: "pescetarian", cost: 3, name: "Pescetarian", description: "Fish is the only food that restores health and hydration" },
    reckless: { id: "reckless", cost: 4, name: "Reckless", description: "You don't handle your tools with care. Items take extra durability damage" },
    sloth: { id: "sloth", cost: 4, name: "Sloth", description: "Your limbs feel heavier. Attack speed is significantly lowered." },
    glass_frame: { id: "glass_frame", cost: 10, name: "Glass Frame", description: "A gust of wind would tear you down. Your grit is always set to 1" },
    bouncy: { id: "bouncy", cost: 5, name: "Bouncy", description: "Getting damaged causes additional knockback to you" },
    hydrophobic: { id: "hydrophobic", cost: 10, name: "Hydrophobic", description: "Damage caused by drowning is doubled." },
    ugly_mug: { id: "ugly_mug", cost: 6, name: "Ugly Mug", description: "A -2 to all Heart attribute rolls." },
    vegetarian: { id: "vegetarian", cost: 8, name: "Vegetarian", description: "Meat based food items provide no healing or hydration" },
    dilution: { id: "dilution", cost: 4, name: "Dilution", description: "The sweat of your palms always wipes away jelly before you can use it." },
    cannibal: { id: "cannibal", cost: 12, name: "Cannibal", description: "If it isn't human flesh, you can't eat it." },
    weighed_down: { id: "weighed_down", cost: 7, name: "Weighed Down", description: "Each piece of armor slows you down" },
    water_weight: { id: "water_weight", cost: 4, name: "Water Weight", description: "You move slower the more health you have" },
    uninspiring: { id: "uninspiring", cost: 10, name: "Uninspiring", description: "Your followers just, feel unmotivated around you. Companions have lower health." },
    untrained: { id: "untrained", cost: 10, name: "Untrained", description: "You can never swing your weapon properly, melee damage is reduced by half." },
    early_bird: { id: "early_bird", cost: 10, name: "early_bird", description: "You gain a -1 to all stats during the night" },
    night_owl: { id: "night_owl", cost: 10, name: "night_owl", description: "You gain a -1 to all stats during the day" }

}