var good_perks = {
    groundpound: { id: "groundpound", type: 0, name: "Ground Pound", cost: 3, description: ["§fDoes a ground pound!", "§3§oUse your pores to propel yourself to the ground", "§3§oblasting water from your impact"] },
    dash: { id: "dash", type: 0, name: "Dash", cost: 3, description: ["§fPropel yourself in the direction you're moving.", "§a+2 Distance per Deft.", "§3§oPropel water from your skin, launching you in a direction."] },
    levitate: { id: "levitate", type: 0, name: "Levitation", cost: 1, description: ["§fLevitate While Active", "§3§oCounteract gravity with a constant", "§3§ostream of water from your feet"] },
    resurface: { id: "resurface", type: 0, name: "Resurface", cost: 1, description: ["§fExpel all your air and shoot towards the water surface"] },
    what_doesnt_kill_you: { id: "what_doesnt_kill_you", type: 1, name: "What Doesn't Kill You...", cost: 4, description: ["§fYour damage is increased the lower your health is.", "§3§oYou unlock more precise movements", "§3§owith all that blood out of the way"] },
    water_warrior: { id: "water_warrior", type: 0, name: "Summon Water Warior", cost: 6, description: ["§fForm a warrior made of water. Sends enemies flying back, but can't survive much damage."] },
    perfect_aim: { id: "perfect_aim", type: 0, name: "Perfect Aim", cost: 2, description: ["§fArrows fire perfectly, ignoring gravity and water", "§3§oYou launch a small bolt of water that helps guide the arrow"] },
    blood_cost: { id: "blood_cost", type: 1, name: "Blood Cost", cost: 0, description: ["§fSuppliment health for hydration when empty", "§3§oBlood has water in it"] },
    animal_lover: { id: "animal_lover", type: 0, name: "Animal Lover", cost: 6, description: ["§fSecrete phermones that make wild animals trust you.", "§fIt's duration is affected by your §cCharm"] },
    jelly_bubble: { id: "jelly_bubble", type: 1, name: "Jelly Bubble", cost: 6, description: ["§fJellied bows create a jelly surface on impact", "§3§oCoat the arrow tip with a glob of water.", "§3§othe water splashes and spread the jelly."] },
    hurricane: { id: "hurricane", type: 0, name: "Hurricane", cost: 10, description: [""] },
    wave_slice: { id: "wave_slice", type: 0, name: "Wave", cost: 6, description: ["§fMelee swings sends out a wave of water"] },
    arrow_recovery: { id: "arrow_recovery", type: 0, name: "Arrow Recovery", cost: 6, description: ["§fRecover the next arrow you shoot, and pull the enemy towards you", "§3§oYou attatch a string of mucus to the arrow, and pull it back"] },
    revenge_attack: { id: "revenge_attack", type: 0, name: "Backsplash", cost: 0, description: ["§fChance to deflect incoming damage", "§fChance is based on §bMind §fAttribute Total", "§3§oYou quickly reason where the strike will land,", "§3§oand blast water to deflect the attack"] },
    lifesteal: { id: "lifesteal", type: 0, name: "Blood Siphon", cost: 2, description: ["§f50% of your damage is converted into restored health", "§3§oDrain the blood of your enemies, and absorb it into you."] },
    invisibility: { id: "refraction", type: 0, name: "Refraction", cost: 2, description: ["§fTurn invisible", "§3§oUse your water to perfectly refract light around you"] },
    conservationist: { id: "conservationist", type: 1, name: "Conservationist", cost: 6, description: ["§fAt the cost of 6 hydration, you continually replenish hydration."] },
    ripple: { id: "ripple", type: 0, name: "Ripple Effect", cost: 4, description: ["When in water, send out a large ripple, pushing enemies back and slightly damaging them"] },
    birthday_armor: { id: "birthday_armor", type: 1, name: "Birthday Armor", cost: 8, description: ["§fYou do +2 damage for each empty slot of armor", "§3§oThe blood in your muscles flows more freely without", "§3§othat armor weighin you down"] },
    icicle: { id: "icicle", type: 0, name: "Icicile", cost: 6, description: ["§fAscend to the ceiling, clinging on an icicle", "§7Crouch to destroy the icicle", "§fMaximum range is determined by §aDeftness"] }
}

var dampening_perks = {
    fragile_feet: { id: "fragile_feet", cost: 2, name: "Fragile Feet", description: ["The threshold for fall damage is smaller, and it deals more damage"] },
    frail_fingers: { id: "frail_fingers", cost: 2, name: "Frail Fingers", description: ["Your grip on the bow string is unreliable."] },
    social_anxiety: { id: "social_anxiety", cost: 4, name: "Social Anxiety", description: ["§fYou take damage upon failing an attribute roll."] },
    winded: { id: "winded", name: "Winded", cost: 4, description: ["Your sprint is slower"] },
    pescetarian: { id: "pescetarian", cost: 3, name: "Pescetarian", description: ["§fFish is the only food that restores §chealth and §bhydration"] },
    reckless: { id: "reckless", cost: 4, name: "Reckless", description: ["You don't handle your tools with care. Items take extra durability damage"] },
    sloth: { id: "sloth", cost: 4, name: "Sloth", description: ["Your limbs feel heavier. Attack speed is significantly lowered."] },
    glass_frame: { id: "glass_frame", cost: 10, name: "Glass Frame", description: ["A gust of wind would tear you down. Your grit is always set to 1"] },
    bouncy: { id: "bouncy", cost: 5, name: "Bouncy", description: ["Getting damaged causes additional knockback to you"] },
    hydrophobic: { id: "hydrophobic", cost: 10, name: "Hydrophobic", description: ["Damage caused by drowning is doubled."] },
    ugly_mug: { id: "ugly_mug", cost: 6, name: "Ugly Mug", description: ["§fA §c-2 §fto all §cHeart attribute rolls."] },
    vegetarian: { id: "vegetarian", cost: 8, name: "Vegetarian", description: ["Meat based food items provide no healing or hydration"] },
    dilution: { id: "dilution", cost: 4, name: "Dilution", description: ["The sweat of your palms always wipes away jelly before you can use it."] },
    cannibal: { id: "cannibal", cost: 12, name: "Cannibal", description: ["If it isn't human flesh, you can't eat it."] },
    weighed_down: { id: "weighed_down", cost: 7, name: "Weighed Down", description: ["Each piece of armor slows you down"] },
    water_weight: { id: "water_weight", cost: 4, name: "Water Weight", description: ["You move slower the more health you have"] },
    uninspiring: { id: "uninspiring", cost: 10, name: "Uninspiring", description: ["Your followers just, feel unmotivated around you. Companions have lower health."] },
    untrained: { id: "untrained", cost: 10, name: "Untrained", description: ["You can never swing your weapon properly, melee damage is reduced by half."] },
    early_bird: { id: "early_bird", cost: 10, name: "Early Bird", description: ["You gain a -1 to all stats during the night"] },
    night_owl: { id: "night_owl", cost: 10, name: "Night", description: ["You gain a -1 to all stats during the day"] }

}